%YAML:1.0

#--------------------------------------------------------------------------------------------
# Info / Statistics / Debug
#--------------------------------------------------------------------------------------------



#--------------------------------------------------------------------------------------------
# Timing Parameters - After every iteration, the respective model will sleept for x micro-secs
#--------------------------------------------------------------------------------------------

Timing/LockSleep: 1000

# Client
Timing/Client/RosRate: 1000
